import DefaultLayout from '@/components/DefaultLayout';
import Link from 'next/link';
import { useRouter } from 'next/router';

const tocsPage = () => {
  const router = useRouter()

  return (
    <DefaultLayout>
        <div className="w-screen text-black bg-white">
            <h1 className="w-screen flex p-5 justify-center border-b-2 border-black bg-white dark:text-black" >Privacy Policy for ngfbeers</h1>
            <p className="p-5">Privacy Policy</p>
            <p className="p-5">Last updated: March 12, 2023</p>
            <p className="p-5 font-courier">
            This Privacy Policy describes Our policies and procedures on the collection, 
            use and disclosure of Your information when You use the Service and tells You 
            about Your privacy rights and how the law protects You.
            </p>
            <p className="p-5">
            We use Your Personal data to provide and improve the Service.
            By using the Service,</p>
            <p className="p-5"> 
            You agree to the collection and use of information in accordance with this Privacy Policy. 
            This Privacy Policy has been created with the help of the Free Privacy Policy Generator.
            </p>
            <p className="p-5">
            We only use Google Analytics to see how many visitors we get, which country they are from,
            and which pages are most popular. The only personal information we would ever have is
            if you were to send a message using the contact form. This requires a name, email and message.
            As explained at the bottom of this page, you can contact us and ask us to delete your 
            personal data at any time.
            </p>
            <p className="p-5"> 
            We will never sell your data, and we will only use it as described above.
            </p>
            <p className="p-5"> 
            At this time, we do not have user accounts on this website, and so we don't use cookies.
            If we do add user accounts, we will update this document and cookies will be used to 
            automatically log in.
            </p>
            <h1 className="p-5 font-black">Interpretation and Definitions</h1>
            <h2 className="p-5 font-black">Interpretation</h2>
            <p className="p-5">
            The words of which the initial letter is capitalized have meanings defined 
            under the following conditions. 
            The following definitions shall have the same meaning regardless 
            of whether they appear in singular or in plural.
            </p>
            <h2 className="p-5">Definitions</h2>
            <p className="p-5">
            For the purposes of this Privacy Policy:
            </p>
            <p className="p-5">
            Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ngfbeers.
            </p>
            <p className="p-5">
            Country refers to: United Kingdom
            </p>
            <p className="p-5">
            Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </p>
            <p className="p-5">
            Personal Data is any information that relates to an identified or identifiable individual.
            </p>
            <p className="p-5">
            Service refers to the Website.
            </p>
            <p className="p-5">
            Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            </p>
            <p className="p-5">
            Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
            </p>
            <p className="p-5">
            Website refers to ngfbeers, accessible from ngfbeers.com
            </p>
            <p className="p-5">
            You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </p>
            <h1 className="p-5 font-black">Collecting and Using Your Personal Data</h1>
            <h1 className="p-5 font-black">
            Types of Data Collected
            </h1>
            <h1 className="p-5 font-black">
            Personal Data
            </h1>
            <p className="p-5">
            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <p className="p-5">
            Email address
            </p>
            <p className="p-5">
            First name and last name
            </p>
            <p className="p-5">
            Usage Data
            </p>
            <h1 className="p-5 font-black">
            Usage Data
            </h1>
            <p className="p-5">
            Usage Data is collected automatically via Google Analytics when using the Service.
            </p>
            <p className="p-5">
            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="p-5">
            Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
            </p>
            <p className="p-5">
            The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country.
            </p>
            <h1 className="p-5 font-black">
            Delete Your Personal Data
            </h1>
            <p className="p-5">
            You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.
            </p>
            <h1 className="p-5 font-black">
            Children's Privacy
            </h1>
            <p className="p-5">
            Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.
            </p>
            <p className="p-5">
            If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
            </p>
            <h1 className="p-5 font-black">
            Links to Other Websites
            </h1>
            <p className="p-5">
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
            <h1 className="p-5 font-black">
            Contact Us
            </h1>
            <p className="p-5">
            If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p className="p-5">
            By email: 
            <button type="button" onClick={() => router.push("mailto:ngfbeers@gmail.com")} className='underline'>ngfbeers@gmail.com</button>
            </p>
            <p className="p-5">
            By visiting this page on our website: <Link href="https://www.ngfbeers.com/contact" target="_blank" className='underline'>Contact Us</Link>
            </p>
        </div>
    </DefaultLayout>
  )
}

export default tocsPage;